<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Suvidha-PC" failures="1" tests="7" name="com.policyBazar.qa.testcases.Login" time="142.021" errors="0" timestamp="2023-10-07T15:16:24 IST" skipped="0">
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithValidCredentials" time="17.594"/>
  <system-out/>
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithValidCredentials" time="17.442"/>
  <system-out/>
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithValidCredentials" time="17.627"/>
  <system-out/>
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithInvalidCredentils" time="18.881"/>
  <system-out/>
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithBlankCredentils" time="31.630"/>
  <system-out/>
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithValidEmailIdandInvalidPassword" time="18.079">
    <failure message="Expected and Actual Does Not Match expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected and Actual Does Not Match expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.policyBazar.qa.testcases.Login.verifyLoginWithValidEmailIdandInvalidPassword(Login.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidEmailIdandInvalidPassword -->
  <system-out/>
  <testcase classname="com.policyBazar.qa.testcases.Login" name="verifyLoginWithINValidEmailIdandValidPassword" time="20.768"/>
  <system-out/>
</testsuite> <!-- com.policyBazar.qa.testcases.Login -->
